# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phi Kappa Theta - Mass Eta
email: pkt-it-active@mit.edu
description: >
  Rush book, photo gallery, and description of the chapter program.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pkt.mit.edu" # the base hostname & protocol for your site
twitter_username: pktweet229
github_username:  pktmasseta
permalink: pretty

# Build settings
markdown: kramdown

collections:
  about:
    output: true
    friendly_name: About
    position: 1
  rush:
    output: true
    friendly_name: Rush
    position: 2
  about:
    output: true
    friendly_name: About
    position: 1
  cpw:
    output: true
    friendly_name: CPW
    position: 3
  brothers:
    output: true
    friendly_name: Brothers
    position: 4
  house:
    output: true
    friendly_name: House
    position: 5
  activities:
    output: true
    friendly_name: Activities
    position: 6
  summer:
    output: true
    friendly_name: Summer
    position: 7
  donate:
    output: true
    friendly_name: Donate
    position: 8


defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: about
    values:
      collection: about
      subtitle: About Us
      banner: banner-outside
  - scope:
      path: ""
      type: rush
    values:
      collection: rush
      banner: rush
      subtitle: Rush Phi Kappa Theta
  
  - scope:
      path: ""
      type: cpw
    values:
      collection: cpw
      banner: cpw
      subtitle: Campus Preview Weekend
  - scope:
      path: ""
      type: brothers
    values:
      collection: brothers
      banner: brothers
      subtitle: Men of Value
      layout: class
  - scope:
      path: ""
      type: house
    values:
      collection: house
      banner: house
      layout: default
  - scope:
      path: ""
      type: activities
    values:
      collection: activities
      banner: party
  - scope:
      path: ""
      type: summer
    values:
      collection: summer
      banner: backbaysummer
      subtitle: Summer Housing
      layout: default
  - scope:
      path: ""
      type: donate
    values:
      collection: donate
      banner: front-patio
      subtitle: Donate to PKT Mass. Eta
      layout: default
